In [1]:
import pandas as pd
import numpy as np

In [2]:
def clean_data(original_df, cvs_path, variable, year=2020):
    df = pd.read_csv(cvs_path, delimiter=',')[['Entity', 'Year',variable]]
    df = df.loc[df['Year'] == 2017]
    df.rename(columns={'Entity': 'Country'}, inplace=True)
    df_copy = original_df.copy()
    df_copy = pd.merge(df_copy, df, on='Country', how='outer').dropna(thresh=5)
    df_copy.drop(columns=['Year'], axis=1, inplace=True)
    return df_copy

In [8]:
main_df = pd.read_csv('../inputs/lifestyle.csv', delimiter=',')

#dropping all city-specific columns
main_df.drop(labels=[
    'Cost of a monthly gym membership(City)',
    'Number of take out places(City)',
    'Cost of a bottle of water(City)',
    'Sunshine hours(City)',
    'Pollution(Index score) (City)',
    'Outdoor activities(City)',
    'Rank'
    ], axis=1, inplace=True)

In [9]:
#Load countries to map capitals to countries
country_city_dt = pd.read_csv('../inputs/world-cities_csv copy.csv', delimiter=',')[['name','country']]
country_city_dt.rename(columns={'name': 'City', 'country': 'Country'}, inplace=True)

In [10]:
#Add countries
main_df = pd.merge(main_df, country_city_dt, on='City', how='outer')

In [11]:
main_df = (main_df
    .dropna(thresh=3)
    .drop_duplicates(subset=['City'])
    .reset_index(drop=True)
)

In [12]:
# urban indicator
df_v1 = clean_data(main_df, '../inputs/urban.csv', 'Urban population (% of total population)')
# press freedom indicator
df_v2 = clean_data(df_v1, '../inputs/press-freedom-rsf.csv', 'Press Freedom Score', 2019)
# poverty rates
df_v3 = clean_data(df_v2, '../inputs/poverty.csv', '$1.90 per day - total number of people below poverty line', 2019)
# number of ppl with depression in 2019
df_v4 = clean_data(df_v3, '../inputs/number-with-depression-by-country.csv', 'Prevalence - Depressive disorders - Sex: Both - Age: All Ages (Number)', 2019)

In [13]:
# share of 1-person households
df_households = pd.read_csv('../inputs/one-person-households.csv', delimiter=',')[['Entity', 'Year', 'Share of one person households']]
df_households.rename(columns={'Entity': 'Country'}, inplace=True)
df = df_households.groupby('Country').agg({'Year': 'max'})
df = pd.merge(df, df_households, on=['Country', 'Year'], how='left')
df_v5 = pd.merge(df_v4, df, on='Country', how='outer').dropna(thresh=5)
df_v5.drop(columns=['Year'], axis=1, inplace=True)

In [14]:
# alcohol consumption
df_alcohol = pd.read_csv('../inputs/alcohol.csv', delimiter=',')[['Entity', 'Year', 'Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)']]
df_alcohol.rename(columns={'Entity': 'Country'}, inplace=True)
df = df_alcohol.groupby('Country').agg({'Year': 'max'})
df = pd.merge(df, df_alcohol, on=['Country', 'Year'], how='left')
df_v6 = pd.merge(df_v5, df, on='Country', how='outer').dropna(thresh=5)
df_v6.drop(columns=['Year'], axis=1, inplace=True)

In [15]:
df_v6

,City,Obesity levels(Country),Life expectancy(years) (Country),Annual avg. hours worked,Happiness levels(Country),Country,Urban population (% of total population),Press Freedom Score,$1.90 per day - total number of people below poverty line,Prevalence - Depressive disorders - Sex: Both - Age: All Ages (Number),Share of one person households,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)"
0,Amsterdam,20.40%,81.2,1434,7.44,Netherlands,91.077,11.28,3.233810e+04,704663.0,38.300000,9.61
1,Sydney,29.00%,82.1,1712,7.22,Australia,85.904,16.02,1.226363e+05,1126306.0,24.991852,10.51
2,Melbourne,29.00%,82.1,1712,7.22,Australia,85.904,16.02,1.226363e+05,1126306.0,24.991852,10.51
3,Vienna,20.10%,81.0,1501,7.29,Austria,58.094,13.47,2.798414e+04,329455.0,37.200000,11.96
4,Stockholm,20.60%,81.8,1452,7.35,Sweden,87.146,8.27,2.497829e+04,477248.0,42.500000,8.93
5,Copenhagen,19.70%,79.8,1380,7.64,Denmark,87.757,10.36,8.123160e+03,235941.0,44.100000,10.26
6,Helsinki,22.20%,80.4,1540,7.80,Finland,85.325,8.92,3.623180e+03,253519.0,43.000000,10.78
7,Fukuoka,4.30%,83.2,1644,5.87,Japan,91.535,29.44,9.228585e+05,3259497.0,34.534599,7.96
8,Tokyo,4.30%,83.2,1644,5.87,Japan,91.535,29.44,9.228585e+05,3259497.0,34.534599,7.96
9,Berlin,22.30%,80.6,1386,7.07,Germany,77.261,14.97,0.000000e+00,3512113.0,41.700000,12.91
10,Frankfurt,22.30%,80.6,1386,7.07,Germany,77.261,14.97,0.000000e+00,3512113.0,41.700000,12.91
11,Barcelona,23.80%,82.2,1686,6.40,Spain,80.080,18.69,3.204482e+05,2594129.0,25.500000,12.72
12,Vancouver,29.40%,81.7,1670,7.23,Canada,81.350,16.53,9.026588e+04,1255399.0,27.576177,8.94
13,Toronto,29.40%,81.7,1670,7.23,Canada,81.350,16.53,9.026588e+04,1255399.0,27.576177,8.94
14,London,27.80%,80.4,1538,7.16,Canada,81.350,16.53,9.026588e+04,1255399.0,27.576177,8.94
15,Beijing,6.20%,75.4,-,5.12,China,57.960,77.66,4.892189e+06,49303509.0,8.589161,7.05
16,Shanghai,6.20%,75.4,-,5.12,China,57.960,77.66,4.892189e+06,49303509.0,8.589161,7.05
17,Bangkok,10.00%,74.1,-,5.99,Thailand,49.200,44.69,2.065747e+04,2472927.0,8.698743,8.30
18,Buenos Aires,28.30%,75.9,-,5.97,Argentina,91.749,25.07,NaN,1130769.0,17.598339,9.65
19,San Francisco,36.20%,78.8,1779,6.94,Argentina,91.749,25.07,NaN,1130769.0,17.598339,9.65
20,Madrid,23.80%,82.2,1686,6.40,Colombia,80.446,41.47,1.969911e+06,1099471.0,11.125908,5.74
21,Jakarta,6.90%,68.5,-,5.28,Indonesia,54.659,39.93,1.179047e+07,6256963.0,8.258493,0.57
22,Seoul,4.70%,81.3,1967,5.87,South Korea,81.503,27.61,1.164195e+05,1330111.0,23.888714,9.70
23,Geneva,19.50%,82.6,1557,7.56,United States,82.058,23.88,4.062069e+06,15119450.0,28.012478,9.87
24,Los Angeles,36.20%,78.8,1779,6.94,United States,82.058,23.88,4.062069e+06,15119450.0,28.012478,9.87
25,Chicago,36.20%,78.8,1779,6.94,United States,82.058,23.88,4.062069e+06,15119450.0,28.012478,9.87
26,Tel Aviv,26.10%,81.9,1898,7.12,Israel,92.336,31.01,2.103344e+04,375278.0,19.656628,4.21
27,Istanbul,32.10%,74.7,1832,5.13,Turkey,74.644,52.98,1.124456e+05,3517286.0,15.300000,2.05
28,Cairo,32.00%,70.7,-,4.15,Egypt,42.705,55.78,2.860944e+06,3462867.0,6.478595,0.36
29,Taipei,6.20%,75.4,-,5.12,Taiwan,NaN,24.37,0.000000e+00,804601.0,NaN,NaN
30,Mumbai,3.90%,67.3,-,3.57,India,33.600,42.94,1.412795e+08,48602578.0,7.664430,5.54
31,Boston,36.20%,78.8,1779,6.94,United Kingdom,83.143,22.26,1.968920e+05,3140877.0,29.900000,11.45
32,Dublin,25.30%,80.5,1772,7.09,Ireland,62.947,14.08,1.169138e+04,225959.0,24.300000,12.88
33,Hong Kong,6.20%,75.4,-,5.51,Hong Kong,100.000,29.46,NaN,NaN,17.058793,NaN
34,Brussels,22.10%,80.4,1583,6.86,Belgium,97.961,12.75,1.682029e+04,464838.0,34.700000,11.08
35,Paris,21.60%,81.8,1505,6.66,France,80.180,22.24,9.110910e+03,2921822.0,36.200000,12.33
36,Sao Paulo,22.10%,73.9,-,6.37,Brazil,86.309,33.58,9.183007e+06,8698146.0,12.000755,7.42
37,Zurich,19.50%,82.6,1557,7.56,Switzerland,73.761,12.13,0.000000e+00,384381.0,38.100000,11.53
38,Johannesburg,28.30%,56.3,-,4.81,South Africa,65.850,20.12,1.085807e+07,2342337.0,26.801935,9.52
39,Milan,19.90%,82.7,1718,6.38,Italy,70.144,26.26,8.584632e+05,2652010.0,32.600000,7.84
40,"Washington, D.C.",36.20%,78.8,1779,6.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,New York,36.20%,78.8,1779,6.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Moscow,23.10%,69.5,1965,5.54,Russia,74.292,49.45,6.255875e+04,5503737.0,25.693902,11.19
43,Mexico City,28.90%,76.4,2137,6.46,Mexico,79.867,48.97,2.405692e+06,4414464.0,10.080218,5.00

In [1]:
df_v6.to_csv('cleaned_data.csv',index=False)

NameError: name 'df_v6' is not defined

relative povert
GDP
extend. by years(?)
quality of life in eiuropean cities